package pr.tongson.lib.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import pr.tongson.lib.greendao.entity.Plan;

import pr.tongson.lib.greendao.dao.PlanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig planDaoConfig;

    private final PlanDao planDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        planDaoConfig = daoConfigMap.get(PlanDao.class).clone();
        planDaoConfig.initIdentityScope(type);

        planDao = new PlanDao(planDaoConfig, this);

        registerDao(Plan.class, planDao);
    }
    
    public void clear() {
        planDaoConfig.clearIdentityScope();
    }

    public PlanDao getPlanDao() {
        return planDao;
    }

}
